import argparse
import os
from pathlib import Path

def init_snap():
    snap_path = Path("snapcraft.yaml")

    if snap_path.exists():
        print("snapcraft.yaml detected.")
        choice = input("Are you sure you want to override it? (y/N): ").strip().lower()

        if choice not in ("y", "yes"):
            print("Aborting. Existing snapcraft.yaml preserved.")
            return

        print("Overwriting existing snapcraft.yaml...")

    else:
        print("No snapcraft.yaml found. Creating a new one...")

    # Placeholder content
    placeholder = """# Generated by Crafty-Snap (R&D mode)
name: example-app
base: core22
version: '0.1'
summary: Example snap generated by Crafty-Snap
description: |
  This is a placeholder snapcraft.yaml generated during R&D. you will need to wait for the real thing to be implemented.
"""

    snap_path.write_text(placeholder)
    print("snapcraft.yaml created successfully!")

def main():
    print("Crafty-Snap: R&D for Snapcraft packaging.")
    parser = argparse.ArgumentParser(prog="crafty-snap", description="Crafty-Snap R&D CLI")
    subparsers = parser.add_subparsers(dest="command")

    # crafty-snap init
    subparsers.add_parser("init", help="Generate a snapcraft.yaml")

    args = parser.parse_args()

    if args.command == "init":
        init_snap()
    else:
        
        print("Nothing works yet, but it's a start.")
        print("Stay tuned...")

if __name__ == "__main__":
    main()

